apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  postgres-user: {{ .Values.postgres.user | b64enc | quote }}
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  postgres-db: {{ .Values.postgres.db | b64enc | quote }}
